---
title: "Model0-2"
output: html_document
date: "2023-04-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning=F)
options(scipen=999)
library(tidyverse)    #Essential Functions
```

## PREP DATASET

How does price change across years and months based on the proportion of negative ratings?

```{r}

steam_games_p = filter(steam_games_final,price!=0,is.na(neg_rate_prop)!=TRUE)
sgf = steam_games_p %>%
  mutate(SPLIT=sample(x=c("TRAIN","TEST"),size=nrow(steam_games_p),
                  replace=T,prob=c(0.85,0.15)))
TRAIN=sgf %>%  filter(SPLIT=="TRAIN")
TEST=sgf %>% filter(SPLIT=="TEST")

TRAIN %>% 
  summarize(mean=mean(price),sd=sd(price),min=min(price),max=max(price))
```


## MODELING USING MODEL 0: predict the price using intercept only
```{r}
# define the function to get fitted values
MODEL0 <- function(DATA, COEF) {
  FIT <- COEF[1]
}

# define the MSE and MAE functions
RMSE0 <- function(DATA, COEF) {
  ERROR <- DATA$price - MODEL0(DATA, COEF)
  LOSS <- sqrt((mean(ERROR^2)))
  return(LOSS)
}

MAE0 <- function(DATA, COEF) {
  ERROR <- DATA$price - MODEL0(DATA, COEF)
  LOSS <- mean(abs(ERROR))
  return(LOSS)
}


set.seed(216)
# define the beta0 values
COEF0 <- tibble(
  beta0 = seq(0, 500, length = 100)
)

COEF0 %>% 
  mutate(RMSE=purrr::map_dbl(beta0,RMSE0,DATA=TRAIN),
         MAE=purrr::map_dbl(beta0,MAE0,DATA=TRAIN),
         rankRMSE=rank(RMSE),rankMAE=rank(MAE)) %>%
         filter(rankRMSE<5,rankMAE<5)

# fit the model using MSE and MAE
BESTRMSE0 <- optim(par = 0, fn = RMSE0, DATA = TRAIN)
BESTRMSE0$par
BESTMAE0 <- optim(par = 0, fn = MAE0, DATA = TRAIN)
BESTMAE0$par



#BESTMSE0$par is the vector of optimal parameters that minimize the mean squared error (MSE) when using the optim() function.

#In this case, BESTMSE0 is the output of the optim() function applied to the MSE0 function, using the TRAIN dataset as input and starting the optimization algorithm with par=0. The optim() function searches for the value of beta0 that minimizes the MSE by iteratively updating beta0 until it converges to the optimal value. The optimal value of beta0 is stored in the par component of the BESTMSE0 object.

```


##MODEL 1A
```{r}
#Model1a 
#Y = Bo + B1X1 + e
#E(Y) = Bo + B1X1
#contains two variables, visualizing price vs. negative proportions

#Model for fitted values 


MODEL1A = function(DATA,COEF){
  FIT = COEF[1]+COEF[2]*DATA$neg_rate_prop
}

RMSE1A = function(DATA,COEF){
  ERROR = DATA$price-MODEL1A(DATA,COEF)
  LOSS = sqrt(mean(ERROR^2))
  return(LOSS)
}

MAE1A = function(DATA,COEF){
  ERROR = DATA$price-MODEL1A(DATA,COEF)
  LOSS = mean(abs(ERROR))
  return(LOSS)
}

set.seed(216)
COEF1A <- tibble(
  beta0 = runif(10000,0,423),
  beta1 = runif(10000,0,423)
)

COEF1A %>% 
  mutate(RMSE=apply(COEF1A,1,RMSE1A,DATA=TRAIN),
         MAE=apply(COEF1A,1,MAE1A,DATA=TRAIN),
         rankRMSE=rank(RMSE),rankMAE=rank(MAE)) %>%
         filter(rankRMSE<5,rankMAE<5)



ggplot(data=filter(TRAIN,price<50)) +
  geom_point(aes(x=neg_rate_prop,y=price),color="lightgreen") +
  geom_abline(aes(intercept=7.12,slope=2.16),color="red",size=1.5)


ggplot(data=filter(TEST,price<50)) +
  geom_point(aes(x=neg_rate_prop,y=price),color="lightgreen") +
  geom_abline(aes(intercept=7.12,slope=2.16),color="red",size=1.5)
```

##MODEL 1B
```{r}

MODEL1B = function(DATA,COEF){
  FIT=COEF[1]+COEF[2]*DATA$release_year
}

RMSE1B=function(DATA,COEF){
  ERROR=DATA$price-MODEL1B(DATA,COEF)
  LOSS=sqrt(mean(ERROR^2))
  return(LOSS)
}

MAE1B=function(DATA,COEF){
  ERROR=DATA$price-MODEL1B(DATA,COEF)
  LOSS=mean(abs(ERROR))
  return(LOSS)
}

set.seed(216)
COEF1B <- tibble(
  beta0 = runif(10000,0,10),
  beta1 = runif(10000,0,10)
)

COEF1B %>% 
  mutate(RMSE=apply(COEF1A,1,RMSE1B,DATA=TRAIN),
         MAE=apply(COEF1A,1,MAE1B,DATA=TRAIN),
         rankRMSE=rank(RMSE),rankMAE=rank(MAE)) %>%
         filter(rankRMSE<5,rankMAE<5)

#Bo and B1
  
TRAIN %>%
  filter(price<100) %>%
  ggplot()+ geom_point(aes(x=as.character(release_year),y=price),color="lightskyblue2") +
    geom_abline(aes(intercept=8.11,slope=0.4),color="white",size=1.5)

TEST %>%
  filter(price<100) %>%
  ggplot()+ geom_point(aes(x=as.character(release_year),y=price),color="lightskyblue2") +
    geom_abline(aes(intercept=8.11,slope=0.4),color="white",size=1.5)

```

##MODEL 2
```{r}

LM2=lm(price~neg_rate_prop+release_year,data=TRAIN)
summary(LM2)
summary(LM2)$sigma #The RSE value is 8.044, however a small RSE can correspond to a large error if the range of prices is quite variable.

RMSE2=function(DATA,COEF){
  ERROR=DATA$price-MODEL2(DATA,COEF)
  LOSS=sqrt(mean(ERROR^2))
  return(LOSS)
}
MAE2=function(DATA,COEF){
  ERROR=DATA$price-MODEL2(DATA,COEF)
  LOSS=mean(abs(ERROR))
  return(LOSS)
}


ggplot(TRAIN, aes(x = release_year, y = price)) +
  geom_point(aes(color = neg_rate_prop),size=3) +
  scale_color_gradient2(low="blue",mid="white",high="green",midpoint=0.5) +
  labs(title = "TRAIN DATA Release Year vs. Price", x = "Release Year", y = "Price", color = "Negative Rate Proportion") +
  theme_minimal() +
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    axis.line = element_line(size = 1),
    axis.text = element_text(size = 12),
    axis.title = element_text(size = 14)
  )

residuals_df <- data.frame(Residuals = resid(LM2), Predicted = predict(LM2))

# Plot the residuals against the predicted values
ggplot(residuals_df, aes(x = Predicted, y = Residuals)) +
  geom_point() +
  geom_hline(yintercept = 0, color = "red") +
  labs(title = "Residual Plot", x = "Predicted Values", y = "Residuals")

#Based off the residual plot, we can tell that the model is overpredicting the price. This can be explained through the dense aggregation of data points above the y=0 residual line.


#generate predicted values on test set
test_preds <- predict(LM2, newdata = TEST)
residuals_df <- data.frame(Residuals = TEST$price - test_preds, Predicted = test_preds)

ggplot(residuals_df, aes(x = Predicted, y = Residuals)) +
  geom_point() +
  geom_hline(yintercept = 0, color = "red") +
  labs(title = "Residual Plot (Test Set)", x = "Predicted Values", y = "Residuals")



MODEL2 = function(DATA,COEF){
  FIT=COEF[1]+COEF[2]*DATA$neg_rate_prop+COEF[3]*DATA$release_year
}

MODEL2.GRAPH = sgf %>% 
  mutate(predict.price=MODEL2(DATA=sgf,COEF=coef(LM2))) %>%
  ggplot()+geom_point(aes(x=price,y=predict.price,
              color=factor(SPLIT,levels=c("TRAIN","TEST"))),alpha=0.2) + 
  theme_minimal() + geom_abline(intercept=0,slope=1) +
  guides(color=guide_legend(title="Dataset")) + xlab("Price") +
  ylab("Predicted Price")
  
```

##TABLE COMPARING MAE AND MSE FOR MODEL 0, 1A, 1B AND 2
```{r}
MODELS=c("MODEL 0","MODEL 1A","MODEL 1B","MODEL 2")
MSE=c(RMSE0(TEST,c(5.05)),
      RMSE1A(TEST,c(7.12,2.16)),
      RMSE1B(TEST,c(8.11,0.4)),
      RMSE2(TEST,c(371.5,-2.53,-0.18)))
MAE=c(MAE0(TEST,c(5.05)),
      MAE1A(TEST,c(2.22,7.56)),
      MAE1B(TEST,c(8.11,0.14)),
      MAE2(TEST,c(371.5,-2.53,-0.18)))
COMPARE=tibble(MODELS=MODELS,MSE=MSE,MAE=MAE)
print(COMPARE)
```

##RIDGE REGRESSION USING THREE-PREDICTOR VARIABLES

```{r}
library(glmnet)

response_var <- steam_games_p$price
predictor_vars <- steam_games_p[,c("neg_rate_prop","release_year","release_month")]
predictor_vars.MATRIX <- as.matrix(predictor_vars)
ridge_mod <- glmnet(x=predictor_vars.MATRIX,y=response_var,alpha=0)
plot(ridge_mod,xvar="lambda")

#As the value of log lambda increases, the penalty term in the objective function becomes more dominant, and the coefficients are shrunk more towards zero. This is why the coefficients converge towards zero as log lambda nears 6

#The fact that the three lines merge as log lambda nears 6 and the coefficients near 0 means that the three predictor variables may not be contributing much to the model's predictive power, and thus their coefficients are shrunk towards zero. This suggests that the model may be overfitting the data if all three predictors are included. To avoid overfitting, it may be necessary to remove some predictors or use a different type of regularization such as Lasso regression.

#In some cases, having a wider range of coefficients can indicate that some predictors are more influential in predicting the outcome variable than others. However, it is important to note that the magnitude of coefficients can also be influenced by the scale of the predictor variables. For example, if one predictor variable is measured in thousands and another in ones, the coefficients for the former variable will be larger, even if it is not necessarily more influential in predicting the outcome variable.

#HOW CAN WE USE THIS FOR PREDICTIONS?

#Ridge regression can be used for both prediction and variable selection. It can help prevent overfitting by shrinking the coefficients of the predictor variables towards zero, and can therefore reduce the variance of the predictions.

cv.obj <- cv.glmnet(x=predictor_vars.MATRIX,y=as.matrix(response_var), alpha = 0, nfolds = 10)
optimal_lambda <- cv.obj$lambda.min #this cross-validation was performed to isolate the optimal lambda value using three predictor variables 

ridge_coef <- coef(ridge_mod,s=0.066) #coef() function is used to obtain the coefficients for the ridge regression with lambda = 0.06.

#intercept = 336, beta1 = -2.75, beta2 = -0.16, beta3 = -0.006



train.model.func <- function(data, beta0, beta1, beta2, beta3) {
  model <- lm(price ~ neg_rate_prop + release_year + release_month, data = data, 
              lambda = 0.066, intercept = beta0, coef = c(beta1, beta2, beta3))
  return(model)
}

BEST.MOD <- steam_games_p %>% 
  mutate(best.model = predict(train.model.func(data = ., beta0 = 336, 
                                                beta1 = -2.75, beta2 = 
                                                 -0.16, 
                                                beta3 = -0.006)))

ggplot(filter(BEST.MOD), aes(x = price, y = best.model)) +
  geom_point(alpha=0.3) +
  xlab("Actual Price") + ylab("Fitted Price") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  xlim(0,30)


```

#polynomial approach?

```{r}
steam_games_sub <- select(steam_games_final, release_year, average_playtime, neg_rate_prop, price) 

set.seed(123)
  
poly <- steam_games_sub %>%
  mutate(split2=sample(x=c("TRAIN","TEST"),size=nrow(steam_games_sub),replace=T,prob=c(0.70,0.30)))
TRAIN_poly=poly %>%  filter(split2=="TRAIN")
TEST_poly=poly %>%  filter(split2=="TEST")

poly_model <- lm(price~poly(release_year,2) + poly(average_playtime, 2) + poly(neg_rate_prop, 2), data = TRAIN_poly)

poly_pred <- predict(poly_model, newdata = TEST_poly)
MAE.func = function(actual, predict){
  sum = 0 
  for (i in seq_along(actual)){
    abs = abs(predict[i] - actual[i])
    sum = sum + abs
  }
  return(sum/length(actual))}
  
MAE_poly = MAE.func(TEST_poly$price, poly_pred)



#making predictions for the next ten years 
poly_years <- data.frame(
  release_year = seq(max(steam_games_sub$release_year) + 1, max(steam_games_sub$release_year) + 10, by = 1), 
  average_playtime = 20, 
  neg_rate_prop = 0.1)

poly_years$pred_price <- predict(poly_model, newdata= poly_years)

#example average playtime and neg_rate_prop chosen as a specific combination
ggplot(poly_years %>% filter(average_playtime == 20, neg_rate_prop == 0.1), aes(x = release_year, y = pred_price)) +
  geom_line() +
  labs(title = "Predicted Price for Games with Specific Playtime and Negative Rating Proportion",
       subtitle = "Average playtime = 20 hours, Negative rating proportion = 0.1",
       x = "Release Year",
       y = "Predicted Price")
poly_years %>% filter(average_playtime == 20, neg_rate_prop == 0.1)

```

